# ===================================================================
#  SUPABASE PostgreSQL Configuration (Pooler - Recommended)
# ===================================================================

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres

# Notice the username is different when using the pooler!
spring.datasource.username=postgres.ndwmvsfcfeemwhdmxwax
spring.datasource.password=s.pradeep@123456789
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Connection pool settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000